### ISSUE TITLE
Can version 2.0 integrate fossils and paleoclimate for analysis?

### ISSUE THREAD

**Issue by Zeroo11** [wxguillo/machuruku#7]
Hello,
Professor.
I have a time-calibrated phylogenetic tree (tip dating using fossils), can I include fossil tips in the analysis? to reconstruct the distribution of ancestors?

**Comment by wxguillo** [comment]
Hi, currently Machuruku only works with an ultrametric tree, ie one where all tips are at the same height (the present). Reconstructed ancestors correspond to nodes and branches in such a tree.
