### ISSUE TITLE
Issue with some variables using machu.1.tip.resp()

### ISSUE THREAD

**Issue by ghost** [wxguillo/machuruku#8]
Hi there,

First of all, thank you so much for this amazing package, you did an amazing work!
I'm however getting a very strange error while using the command machu.1.tip.resp(). 
I have several variables, they all have the exact properties and settings, instead of only using bioclimatic variables, I'm also trying to use soil variables. Somehow, only certain variables work with the command but I can't figure why since they have all the same parameters. 

I have also tried using bioclimatic variables for the entire world in a lower resolution (0.25 x 0.25) and for some reasons, the command works for some variables but not for all the bioclimatic variables. However, if I convert these bioclimatic variables to the same extent and resolution of the bioclimatic variables from your tutorial, they all work but this "trick" only works with the bioclimatic variables and not with other variables. So for example, if I try using bio4 (world map, 0.25 x 0.25) it doesn't work while bio2 (world map) does, however if I convert bio4 to your resolution and area, it works. But this trick doesn't work for some variables.

Here is an example using your tutorial example, a variable called SMO which works perfectly fine and a variable called SBD which returns me an error (see below).
```
> SMO
class      : RasterLayer 
dimensions : 164, 127, 20828  (nrow, ncol, ncell)
resolution : 0.08333354, 0.08333335  (x, y)
extent     : -81.49866, -70.9153, -14.05614, -0.38947  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs
source     : SMO.grd 
names      : SMO 
values     : 0.09407494, 0.3642818  (min, max)

> summary(SMO)
                 SMO
Min.    9.407494e-02
1st Qu. 2.605851e-01
Median  2.945222e-01
3rd Qu. 3.174641e-01
Max.    3.642818e-01
NA's    4.041000e+03

> SBD
class      : RasterLayer 
dimensions : 164, 127, 20828  (nrow, ncol, ncell)
resolution : 0.08333354, 0.08333335  (x, y)
extent     : -81.49866, -70.9153, -14.05614, -0.38947  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs
source     : SBD.grd 
names      : SBD 
values     : 78, 154  (min, max)

> summary(SBD)
         SBD
Min.      78
1st Qu.  123
Median   128
3rd Qu.  134
Max.     154
NA's    4431
```

Now here is me trying to perform the command with bioclimatic variables, SMO and SBD:
```
> current <- stack(bio1, bio4, bio8, bio9, bio10, bio11, bio12, bio13,
+                  bio14, bio15, bio16, bio17, bio18, bio19)
> full <- stack(current, SMO, SBD)
> full 
class      : RasterStack 
dimensions : 164, 127, 20828, 16  (nrow, ncol, ncell, nlayers)
resolution : 0.08333333, 0.08333333  (x, y)
extent     : -81.49866, -70.91533, -14.05614, -0.3894694  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs 
names      :        bio_1,        bio_4,        bio_8,        bio_9,       bio_10,       bio_11,       bio_12,       bio_13,       bio_14,       bio_15,       bio_16,       bio_17,       bio_18,       bio_19,          SMO, ... 
min values :   5.34999990, 193.11000061,  17.85000038, -10.81999969,  17.85000038, -18.17000008,   3.50999999,   1.50999999,   0.00000000,   6.00000000,   4.01999998,   0.00000000,   3.50999999,   0.00000000,   0.09407494, ... 
max values :  260.7200012, 2181.2900391,  270.9800110,  259.6000061,  270.9800110,  255.9700012, 5691.7402344,  727.1599731,  352.1199951,  235.5700073, 2045.3800049, 1065.7700195, 1861.0799561, 2044.9000244,    0.3642818, ... 

> resp <- machu.1.tip.resp(occ, full)
**Error in if (abs(galton) < max.GB) interp.alpha(abs(galton)) else { : 
  missing value where TRUE/FALSE needed**
```
If I remove SBD, the error disappears and everything works perfectly.

I have tried with other variables and the error happens with some others as well but it also works very well with others so it's very strange. I also get a slightly different error sometimes, working with other variables:
`**Error in if (abs(gamma1) > max.gamma1) gamma1 <- sign(gamma1) * 0.9 *  : 
  missing value where TRUE/FALSE needed**`

Here is what I've already tried but didn't work: 
- NAs is not an issue since variables that work have NAs and variables that don't as well
- 0 is not an issue as well 
- 1st quartile being = 0 is more present for not working variables but one variable works with a 1st quartile = 0, so I guess it's not the issue
- I've tried replacing all low values by 0, did not work
- I've tried only stacking the variables that do not work together but doesn't work
- I've tried putting less variables but still doesn't work
- I've tried converting my .grd files tp .tif, doesn't work

I don't know really know what else I can do anymore.. So if you have any ideas, I'd be very thankful!

Thank you so much,

Ed
#

**Comment by CarbonEd14** [comment]
Going further with the commands using the bioclimatic variables as well as the working variable SMO for the machu.1 will give me the following error for machu.2:
`ace <- machu.2.ace(resp, tree, timeslice=c(0.787), unc=T)
Warning message:
In sqrt(1/out$hessian) : NaNs produced`

**Comment by wxguillo** [comment]
Hi Ed, my guess is that it's some quirk of the raster's format, but I can't say what without exploring the rasters and how they interact with my code directly. My suggestion is to try going through my code for machu.1.tip.resp line by line (you can get the code from my github or just by typing in the function name without parentheses in R) until you identify exactly which line is throwing the error. Then you and I can work on a solution. You'll have to email me your dataset if you want me to get my hands dirty with it.
Best,
Wilson

**Comment by ghost** [comment]
Hi Wilson,

Thank you for your quick reply. I've managed to make it somehow work for your resolution and region by resampling my layers to your layers using resample() with the method = "cubic" instead of neighbor. 
I can't try it using my own data yet as I haven't made the phylogenetic tree but once I do, if I encounter the same issues using my variables with the resolution and region I need, I'll get back to you. 

Best regards,

Ed
